### ISSUE TITLE
Easier way to change a project's bundle name with the new android build system?

### ISSUE THREAD

**Issue by iProgramMC** [SethRobinson/proton#17]
The current build system thing has a major flaw: all applications generated by it are called `com.rtsoft.RTAndroidApp`. This is OK-ish if you're only building one application using Proton SDK, but good luck building two or more with the same 'shared' files. Is this going to be changed?

**Comment by SethRobinson** [comment]
That's the beauty of the new system - just edit local.properties and change the app id there and the entire build will use it instead.  Everything in shared can stay com.rtsoft.RTAndroidApp, it won't matter.

**Comment by iProgramMC** [comment]
I have tried this. The shared stuff stays as "Java_com_rtsoft_RTAndroidApp_XXX" and I get crashes unless I change the function name to "Java_com_iprogramincpp_myprojectnamehere" or something

**Comment by SethRobinson** [comment]
Hmm - I suspect you might have changed one you shouldn't have maybe?  

Make sure you DIDN'T change the ID in AndroidGradle\app\build.gradle, AndroidGradle\app\src\main\java\com\rtsoft\RTAndroidApp\Main.java or AndroidGradle\app\src\main\cpp\CMakeList.txt.

I was about to tell you to compile RTBareBones's android project as a test, but it looks like to me I might have made a mistake and it's not fully updated on github. (Sorry!) 

Please try RTSimpleApp instead.  If you search for where com.rtsoft.rtsimpleapp is you should see it's only in local.properties_removethispart_ (remove the _removethispart and edit in your keystore/password stuff, otherwise it can't produce a release bundle)

Dink, Mind Wall and Dungeon Scroll on the Play store are all using this build system, so in theory this should work.  Let me know what happens, I'll update the docs to be better, this is my fault!

**Comment by iProgramMC** [comment]
Right, I use RTBareBones, and I have changed the folder structure from com/rtsoft/RTAndroidApp, but I will try both RTBareBones and RTSimpleApp just changing the package name in the local.properties.

**Comment by SethRobinson** [comment]
RTSimpleApp should compile and run without problems - but keep in mind if you DO change the package name, it HAS to match the patch name in App.cpp as well.  (AndroidUtils.cpp uses it when it does 
 SetJavaPackageName(string(GetBundlePrefix())+string(GetBundleName())); )
		

look for:

const char * GetBundleName()
{
	const char * bundleName = "rtsimpleapp";
	return bundleName;
}

and make sure that matches what you changed it to.

**Comment by iProgramMC** [comment]
![image](https://user-images.githubusercontent.com/17717494/181824910-9337593c-5c22-4d4c-b52f-707283da61d1.png)
Well, that doesn't look right.

![image](https://user-images.githubusercontent.com/17717494/181825537-8a4c7471-c810-486d-a71c-66cb0ef6c34c.png)
Seems I need fmod? I'll try disabling that

**Comment by SethRobinson** [comment]
I don't understand how I got a notification about a post here (the one with screenshots) that isn't actually in this thread, heh.  Anyway, I've recently switched machines again so I'm going to go through the process of installing android studio etc and building these.  If it's setup for FMOD in rtsimpleapp, yeah, that's a mistake, I'll switch it back to the default android audio system.

**Comment by iProgramMC** [comment]
Sorry. I deleted the comment because I messed up something

**Comment by SethRobinson** [comment]
I updated the gradle files for both sample projects.  Removed fmod from rtsimpleapp, hopefully it works for ya now

**Comment by ChristianIQ** [comment]
okey
